package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"github.com/spf13/cobra"

	"github.com/drizz-dev/drizz-farm/internal/android"
)

var setupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Interactive setup wizard for drizz-farm",
	Long:  "Detects hardware, recommends pool configuration, downloads system images, and creates config.",
	RunE:  runSetup,
}

func init() {
	rootCmd.AddCommand(setupCmd)
}

func runSetup(cmd *cobra.Command, args []string) error {
	fmt.Println("drizz-farm Setup Wizard")
	fmt.Println("━━━━━━━━━━━━━━━━━━━━━━")
	fmt.Println()

	// Detect hardware
	fmt.Printf("Platform: %s/%s (%d CPUs)\n", runtime.GOOS, runtime.GOARCH, runtime.NumCPU())

	// Detect SDK
	sdk, err := android.DetectSDK()
	if err != nil {
		fmt.Printf("\nAndroid SDK not found: %v\n", err)
		fmt.Println("\nPlease install Android SDK command-line tools:")
		fmt.Println("  brew install --cask android-commandlinetools")
		fmt.Println("  OR: https://developer.android.com/studio#command-tools")
		return nil
	}
	fmt.Printf("Android SDK: %s\n", sdk.Root)

	if err := sdk.Validate(); err != nil {
		fmt.Printf("SDK validation: %v\n", err)
		fmt.Println("\nSome SDK tools are missing. Install them with:")
		fmt.Println("  sdkmanager --install 'platform-tools' 'emulator'")
		return nil
	}
	fmt.Println("SDK tools: OK")

	// Create config directory
	home, _ := os.UserHomeDir()
	configDir := filepath.Join(home, ".drizz-farm")
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	configPath := filepath.Join(configDir, "config.yaml")
	if _, err := os.Stat(configPath); err == nil {
		fmt.Printf("\nConfig already exists: %s\n", configPath)
		fmt.Println("Delete it and re-run setup to regenerate.")
		return nil
	}

	// Generate config
	config := generateDefaultConfig(runtime.NumCPU())
	if err := os.WriteFile(configPath, []byte(config), 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	fmt.Printf("\nConfig written to: %s\n", configPath)
	fmt.Println("\nNext steps:")
	fmt.Println("  1. Review the config: cat ~/.drizz-farm/config.yaml")
	fmt.Println("  2. Start the daemon:  drizz-farm start")
	fmt.Println("  3. Check status:      drizz-farm status")

	return nil
}

func generateDefaultConfig(numCPU int) string {
	// Conservative: ~2 emulators per 4 cores
	maxEmulators := numCPU / 2
	if maxEmulators < 2 {
		maxEmulators = 2
	}
	if maxEmulators > 8 {
		maxEmulators = 8
	}

	warmCount := maxEmulators / 2
	if warmCount < 1 {
		warmCount = 1
	}

	return fmt.Sprintf(`# drizz-farm configuration
# Generated by drizz-farm setup

node:
  name: ""  # auto-detected from hostname
  log_level: "info"

pool:
  max_concurrent: %d
  session_timeout_minutes: 60
  session_max_duration_minutes: 180
  queue_max_size: 20
  queue_timeout_seconds: 300
  port_range_min: 5554
  port_range_max: 5700

  warmup:
    - profile: "pixel_7_api34"
      count: %d

  profiles:
    android:
      pixel_7_api34:
        device: "pixel_7"
        system_image: "system-images;android-34;google_apis;arm64-v8a"
        ram_mb: 2048
        heap_mb: 512
        disk_size_mb: 4096
        gpu: "host"
        snapshot: true
        boot_timeout_seconds: 120

      pixel_8_api35:
        device: "pixel_8"
        system_image: "system-images;android-35;google_apis;arm64-v8a"
        ram_mb: 2048
        heap_mb: 512
        disk_size_mb: 4096
        gpu: "host"
        snapshot: true
        boot_timeout_seconds: 120

api:
  host: "0.0.0.0"
  port: 9401
  grpc_port: 9400

network:
  allowed_cidrs:
    - "192.168.0.0/16"
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "127.0.0.0/8"
  mdns:
    enabled: true
    service_type: "_drizz-farm._tcp"

health_check:
  interval_seconds: 15
  unhealthy_threshold: 3

cleanup:
  on_session_end: "snapshot_restore"
  orphan_check_interval_seconds: 60
  disk_cleanup_threshold_gb: 20

artifacts:
  video_recording: true
  screenshot_on_failure: true
  logcat_capture: true
  network_har_capture: false
  retention_days: 30
`, maxEmulators, warmCount)
}
