#!/usr/bin/env bash
# update-formula.sh — regenerate the Homebrew formula for a new release.
#
# Flow:
#   1. `make release` has just built dist/drizz-farm-<VERSION>-darwin-universal.tar.gz
#      and dist/SHA256SUMS.
#   2. This script reads the version + SHA256, renders a formula to stdout.
#   3. You pipe it into the tap repo (drizz-ai/homebrew-tap/Formula/drizz-farm.rb)
#      and push that repo. Homebrew users get the new version immediately.
#
# Usage:
#   ./packaging/homebrew/update-formula.sh v0.1.0 > ~/code/homebrew-tap/Formula/drizz-farm.rb
#
# Requires: the `dist/` directory from `make release`.

set -euo pipefail

VERSION="${1:-}"
if [[ -z "$VERSION" ]]; then
  echo "usage: $0 <version>   (e.g. v0.1.0)" >&2
  exit 1
fi

# Allow either "v0.1.0" or "0.1.0" as input; normalize.
VERSION_NO_V="${VERSION#v}"
TAG="v${VERSION_NO_V}"

DIST_DIR="$(cd "$(dirname "$0")/../.." && pwd)/dist"
TARBALL="drizz-farm-${TAG}-darwin-universal.tar.gz"
TARBALL_PATH="$DIST_DIR/$TARBALL"

if [[ ! -f "$TARBALL_PATH" ]]; then
  echo "missing release artifact: $TARBALL_PATH" >&2
  echo "hint: run 'make release' first" >&2
  exit 1
fi

SHA256=$(shasum -a 256 "$TARBALL_PATH" | cut -d ' ' -f 1)

cat <<EOF
# frozen_string_literal: true

# Homebrew formula for drizz-farm ${TAG}.
# Auto-generated by packaging/homebrew/update-formula.sh — do not hand-edit
# the copy in the tap repo; regenerate and push instead.
class DrizzFarm < Formula
  desc "Self-hosted Android emulator pool — a device lab on your own Mac"
  homepage "https://drizz.ai"
  version "${VERSION_NO_V}"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/parthadrizz/drizz-farm/releases/download/${TAG}/${TARBALL}"
    sha256 "${SHA256}"
  end

  def install
    bin.install "drizz-farm-darwin-universal" => "drizz-farm"
  end

  def caveats
    <<~EOS
      drizz-farm is installed. Finish setup with:

        drizz-farm setup        # detect Android SDK, install as a background service
        drizz-farm start        # or start manually

      Dashboard: http://\$(hostname).local:9401
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/drizz-farm version")
  end
end
EOF
